### PR TITLE
refactor: prefer concat (++) over hand crafting names

### PR DESCRIPTION
**Pull request by Equilibris**
Throughout Ind.lean I use ugly constructors and helper functions to do the job of what could simply be done with `++`, this fixes that.

This is a non-functional change

### CODE REVIEW

**Comment by tobiasgrosser** [comment]
Replace `This PR is non functional` with `This is a non-functional change`. :-)

**Review by tobiasgrosser — APPROVED** [review]
This seems to be a clear improvement and probably ready to go in.

**Review by AtticusKuhn — APPROVED** [review]
Very good PR. Looks good to me.

**Review by alexkeizer — APPROVED** [review]
Lovely, it's always nice when a PR has more deletions than additions. LGTM!

**Pull request merged**
